### ISSUE TITLE
[DATA]

### ISSUE THREAD

**Issue by MaxChevalier** [Yarkis01/PokeAPI#39]
# Informations
URL: https://api-pokemon-fr.vercel.app/api/v1/pokemon/253

# Problème
Probleme de nom dans son évolution

# Données actuelles
```json
{
"next": [
            {
                "pokedexId": 254,
                "name": "Massko",
                "condition": "Niveau 36"
            }
        ]
}
```

# Données souhaitées
```json
{
"next": [
            {
                "pokedexId": 254,
                "name": "Jungko",
                "condition": "Niveau 36"
            }
        ]
}
```

**Comment by Yarkis01** [comment]
Corrigé dans la version [7229314](https://github.com/Yarkis01/PokeAPI/commit/7229314b3ee030ac47cd44b5fa16a250c9ab6554).
