### ISSUE TITLE
condition pre-évolution

### ISSUE THREAD

**Issue by Kevin-Adrea** [Yarkis01/PokeAPI#43]
# Informations
URL: https://api-pokemon-fr.vercel.app/api/v1/pokemon/26

# Problème
On n'a pas les conditions d'évolution dans le cas d'une pré-évolution 

Exemple sur la fiche de Pikachu : 
"next": [{"pokedexId": 26, "name": "Raichu", "condition": "Pierre Foudre"}]

et sur la fiche de Raichu :
"pre": [{"pokedexId": 172, "name": "Pichu"}, {"pokedexId": 25, "name": "Pikachu"}]

Serait-il possible d'inclure les conditions dans le tableau "pre" ? Ou y'a-t-il une autre solution pour avoir cette information sans aller chercher sur la fiche du Pokémon suivant ?

Merci !!

# Données actuelles
```json
{
"pre": [{"pokedexId": 172, "name": "Pichu"}, {"pokedexId": 25, "name": "Pikachu"}]
}
```

# Données souhaitées
```json
{
"pre": [{"pokedexId": 172, "name": "Pichu"}, {"pokedexId": 25, "name": "Pikachu", "condition": "Pierre Foudre"}]
}
```

**Comment by Yarkis01** [comment]
👋🏻 Nous n'avions pas mis les conditions d'évolutions sur les pré, car nous n'en avions pas vu l'utilité et que cela était un choix dès le départ du projet (probablement mauvais, mais on ne va rien dire).
Actuellement, il n'existe aucun autre moyen que de récupérer la page Pokémon des pré pour pouvoir avoir leurs évolutions, mais nous allons probablement les rajouter d'ici quelque temps.
