### ISSUE TITLE
[DATA] Nom d'un Pokémon mal orthographié

### ISSUE THREAD

**Issue by demarbre1u** [Yarkis01/PokeAPI#53]
# Informations
URL: https://api-pokemon-fr.vercel.app/api/v1/pokemon

# Problème
Lors de la récupération de la liste des Pokémon, j'ai remarqué que le nom de Polthégeist était mal orthographié : 
Il y a écrit "Polthégheist" à la place de "Polthégeist".

J'imagine qu'il doit également y avoir des impacts sur toutes les routes qui pourraient concerner ce Pokémon.

cf: https://www.pokepedia.fr/Polth%C3%A9geist

# Données actuelles
```json
{
    "name": {
        "fr": "Polthégheist",
        "en": "Polteageist",
        "jp": "ポットデス"
    },
}
```

# Données souhaitées
```json
{
    "name": {
        "fr": "Polthégeist",
        "en": "Polteageist",
        "jp": "ポットデス"
    },
}
```

**Comment by Yarkis01** [comment]
:wave: Données corrigées, merci pour le signalement.
