### ISSUE TITLE
[DATA] Oublie de la clef "next" pour les évolutions de Baggaïd ?

### ISSUE THREAD

**Issue by LassaInora** [Yarkis01/PokeAPI#58]
# Informations
URL: https://tyradex.tech/api/v1/pokemon/560

# Problème
Automitisation complexe avec le double cas d'inexistance d'évolutions (valeur null et absence de valeur qui coexiste) rendant son utilisation lourde.

# Données actuelles
```json
{
  "pre": [
    {"pokedexId": 559, "name": "Baggiguane", "condition": "Niveau 39"}
  ], 
  "mega": null
}
```

# Données souhaitées
```json
{
  "pre": [
    {"pokedexId": 559, "name": "Baggiguane", "condition": "Niveau 39"}
  ], 
  "next": null,
  "mega": null
}
```

**Comment by Ashzuu** [comment]
Bonjour,

Je vous remercie pour votre retour, la correction sera modifié d'ici quelques minutes.

En vous souhaitant une très bonne journée,

Bien Cordialement
